### ISSUE TITLE
Adding Final Project detail in Section 2 - Federated Learning.ipynb 

### ISSUE THREAD

**Issue by gargarchit** [udacity/private-ai#7]
Hi @iamtrask 
Details or Data of Final Project in Section 2 - Federated Learning.ipynb is Absent
i.e Project Description and Data
#UdacityFacebookScholar

**Comment by burhanusman** [comment]
Hi @gargarchit , Do you know if they have added the the project description yet?

**Comment by gargarchit** [comment]
@burhanusman No, I have created a pull request regarding this
may @iamtrask add it early as possible

**Comment by gargarchit** [comment]
@burhanusman You can checkout https://github.com/udacity/private-ai/pull/10
